### ISSUE TITLE
Unable to config fallback key

### ISSUE THREAD

**Issue by Alsan** [pguedes/gesticle#2]
As in the configuration section of the readme,

```text
For example, if the active application window is gedit, and the detected gesture is a 3 finger swipe, the preferred setting will be swipe.down.3.gedit and if that is not configured will look for a swipe.down.3
```

But how can I define both key hash and table name at the same time? For example:

```toml
[swipe.left]
3 = "super+s"
  [swipe.left.3]
  codium = "ctrl+tab"
```

will cause a `Key '3' has already been defined` error.
