### ISSUE TITLE
support disabling a mapping

### ISSUE THREAD

**Issue by pguedes** [pguedes/gesticle#6]
currently the only way to disable a gesture mapping would be to remove all mappings (for all possible applications) of that gesture as if it is not found for a specific app it would fallback to executing the default mapping

we should have a special mapping to signify `do nothing!` so that we could disable a gesture action for a specific app without impacting that gesture on other apps

**Comment by Alsan** [comment]
why not just modify the config toml for that gesture? somethings like:

```toml
[swipe.left]
3-disabled = "key1"
4 = "key2"

[code.swipe.left]
3 = "key3"
4 = "key4"
```
